name: Docker Build (No Login)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image (No Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Disable pushing to registry
          tags: khalilkhan78611/youtube-mp3-converter:local-build
