name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }}
          
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Test the image
      - name: Test Docker image
        run: |
          docker run --rm -d -p 5001:5001 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
          sleep 10
          curl --fail http://localhost:5001/health || exit 1
          docker stop test-container
